version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn clean test
workflows:
  build-and-test:
    jobs:
      - test-java